language: java
jdk:
  - oraclejdk8
  
dist: trusty

addons:
  apt:
     packages:
        - libglew-dev
        - freeglut3-dev
        - libxi-dev
        - libxmu-dev
        - xserver-xorg-video-dummy
        - xpra
        - xorg-dev
        - opencl-headers
        - libgl1-mesa-dev
        - libxcursor-dev
        - libpulse-dev
        - libxinerama-dev
        - libxrandr-dev
        - libxv-dev
        - libasound2-dev
        - libudev-dev
        - mesa-utils
        - libgl1-mesa-glx
        
before_install:
  - sudo add-apt-repository -y ppa:oibaf/graphics-drivers
  - sudo apt-get update -qq -y
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-get -yq --force-yes install libgl1-mesa-dev libgl1-mesa-glx mesa-common-dev libglapi-mesa libgbm1 libgl1-mesa-dri libxatracker-dev xvfb
  
before_script:
  - export DISPLAY=:99
  - export LIBGL_ALWAYS_SOFTWARE=1
  - xpra --xvfb="Xorg +extension GLX +extension RANDR +extension RENDER -config `pwd`/test/dummy.xorg.conf -logfile ${HOME}/.xpra/xorg.log"  start :99
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render;
  - sleep 3
#  - glxinfo
  
install: gradle assemble

script:
  - LIBGL_ALWAYS_SOFTWARE=1 gradle test
  - curl https://build.luxvacuos.net/git/notifyCommit?url=https://github.com/Lux-Vacuos/Voxel.git